-------------------------------------------------------------------------------
Test set: Demo Blaze Functionality
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 19.168 s <<< FAILURE! - in Demo Blaze Functionality
Demo Blaze Functionality.User can go through product categories  Time elapsed: 19.168 s  <<< ERROR!
org.openqa.selenium.NoSuchSessionException: 
invalid session id
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-DBV7AS00', ip: '192.168.1.153', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.114, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: C:\Users\husey\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:64997}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 1b74c23a6e0495021cfb7f3bc661668e

Demo Blaze Functionality.User can go through product categories  Time elapsed: 0 s  <<< ERROR!
org.openqa.selenium.WebDriverException: 
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:34898
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-DBV7AS00', ip: '192.168.1.153', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: driver.version: RemoteWebDriver
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:34898
Caused by: java.net.ConnectException: Connection refused: connect

